version: "3"
services:
  todof:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app/
      - /app/node_modules
    # command: sh -c "/bin/bash"
    command: sh -c "yarn start"
    ports:
      - "3000:3000"

    stdin_open: true
